import { describe, expect, it } from 'vitest';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { AgeConfirmation, ContactForm, MobileNavigation, OrderPanel } from '@/components/interactive';
import { ComplianceFields, FAQAccordion, Header, Footer } from '@/components/ui';

describe('Navigation', () => {
  it('provides all main and policy routes', () => { render(<><Header/><Footer/></>); for (const href of ['/', '/product', '/faq', '/contact', '/shipping-returns', '/privacy', '/terms', '/disclaimer']) expect(screen.getAllByRole('link').some(a => a.getAttribute('href') === href)).toBe(true); });
  it('opens mobile menu, closes on selection and restores focus with Escape', async () => { const user = userEvent.setup(); render(<MobileNavigation/>); const toggle = screen.getByRole('button', { name: /Menu/ }); await user.click(toggle); expect(toggle).toHaveAttribute('aria-expanded','true'); await user.click(screen.getByRole('link', { name:'Home' })); expect(toggle).toHaveAttribute('aria-expanded','false'); await user.click(toggle); await user.keyboard('{Escape}'); expect(toggle).toHaveFocus(); expect(toggle).toHaveAttribute('aria-expanded','false'); });
});
it('updates WhatsApp quantity and enforces lower bound', async () => { const user = userEvent.setup(); render(<OrderPanel/>); expect(screen.getByRole('button', { name:'Decrease quantity' })).toBeDisabled(); await user.click(screen.getByRole('button', { name:'Increase quantity' })); expect(screen.getByLabelText('Quantity')).toHaveTextContent('2'); expect(new URL(screen.getByRole('link', { name:/Order via WhatsApp/ }).getAttribute('href')!).searchParams.get('text')).toContain('2 units of POWER ZOOX'); await user.click(screen.getByRole('button', { name:'Decrease quantity' })); expect(screen.getByLabelText('Quantity')).toHaveTextContent('1'); });
it('opens an age dialog and remembers confirmation', async () => { const user = userEvent.setup(); const view = render(<AgeConfirmation/>); const dialog = screen.getByRole('dialog'); expect(dialog).toHaveAttribute('open'); await user.click(screen.getByRole('button', { name:/I am 18/ })); expect(localStorage.getItem('bhw-adult')).toBe('true'); expect(dialog).not.toHaveAttribute('open'); view.unmount(); render(<AgeConfirmation/>); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); });
it('offers an exit from the age notice', () => { render(<AgeConfirmation/>); expect(screen.getByRole('link', { name:'Leave website' })).toHaveAttribute('href','https://www.google.com/'); });
it('uses a native expandable FAQ', async () => { const user = userEvent.setup(); render(<FAQAccordion/>); const summary = screen.getByText('How do I place an order?'); await user.click(summary); expect(summary.closest('details')).toHaveAttribute('open'); });
it('renders no compliance fields when empty, and only supplied fields', () => { const view = render(<ComplianceFields values={{}}/>); expect(view.container).toBeEmptyDOMElement(); expect(screen.queryByText(/NAFDAC/)).not.toBeInTheDocument(); view.rerender(<ComplianceFields values={{ manufacturer: 'Verified test manufacturer' }}/>); expect(screen.getByText('Verified test manufacturer')).toBeInTheDocument(); expect(screen.queryByText(/NAFDAC/)).not.toBeInTheDocument(); });
it('validates contact and prepares a message without pretending to send', async () => { const user = userEvent.setup(); render(<ContactForm/>); await user.click(screen.getByRole('button',{ name:/Prepare WhatsApp/ })); expect(screen.getByRole('alert')).toHaveTextContent('Enter a valid email address or phone number.'); await user.type(screen.getByLabelText(/Your name/),'Ada'); await user.type(screen.getByLabelText(/Email or phone/),'ada@example.com'); await user.selectOptions(screen.getByLabelText(/Subject/),'Delivery question'); await user.type(screen.getByLabelText(/Your message/),'Can you confirm delivery to my area?'); await user.click(screen.getByRole('checkbox')); await user.click(screen.getByRole('button',{ name:/Prepare WhatsApp/ })); const status = screen.getByRole('status'); expect(status).toHaveTextContent('It has not been sent.'); const url = new URL(within(status).getByRole('link').getAttribute('href')!); expect(url.searchParams.get('text')).toContain('Ada'); await user.type(screen.getByLabelText(/Your name/),' M'); expect(screen.queryByRole('status')).not.toBeInTheDocument(); });
