import Link from 'next/link';
import { ProductGallery, WhatsAppOrderButton } from '@/components/interactive';
import { SectionHeading, ProductCard, Ingredients, HowToOrder, FAQAccordion, FinalCTA, DisclaimerNotice, Testimonials } from '@/components/ui';
import { pageMetadata } from '@/lib/seo';
export const metadata = pageMetadata('Natural Wellness for Everyday Confidence', 'Thoughtful herbal wellness for adult men in Nigeria. Explore POWER ZOOX and enquire discreetly through Blessing Herbal Wellness on WhatsApp.', '/');
export default function Home() { return <><section className="hero container"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-line"/> ROOTED IN NATURE. FOCUSED ON YOU.</span><h1>Natural Wellness<br/>for Everyday<br/><em>Confidence.</em></h1><p>Thoughtfully formulated herbal wellness for adult men who value vitality, confidence and discreet service.</p><div className="hero-actions"><WhatsAppOrderButton/><Link className="text-link" href="/product">Learn About the Product <span aria-hidden="true">→</span></Link></div><div className="adult-note"><span>18+</span><p>Made for adult men.<br/>A considered approach to everyday wellness.</p></div></div><ProductGallery hero/></section>
    <div className="trust-strip"><div className="container">{[['◇', 'Discreet service'], ['↗', 'Convenient ordering'], ['◎', 'Customer support'], ['≡', 'Clear product information']].map(([icon, text]) => <span key={text}><b aria-hidden="true">{icon}</b>{text}</span>)}</div></div>
    <ProductCard/>
    <section className="benefits-section"><div className="container section"><SectionHeading eyebrow="WELLNESS, WITH INTENTION" title="Small rituals. A more considered everyday.">A thoughtful routine starts with informed choices, balanced habits and care for yourself.</SectionHeading><div className="benefits">{[['01', 'Make room for vitality', 'Explore general wellness as part of a balanced everyday routine.'], ['02', 'An active approach', 'Complement your wellness choices with movement, rest and balanced nutrition.'], ['03', 'Keep it considered', 'Learn about the product and its verified label before beginning a routine.'], ['04', 'Keep it personal', 'Enjoy private, one-to-one ordering and space to ask your questions.']].map(([n, title, text]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="small muted">Individual experiences can vary. These are wellness principles, not verified product outcomes.</p></div></section>
    <section className="section container ingredients-section"><SectionHeading eyebrow="TRANSPARENCY COMES FIRST" title="Know what goes into your wellness.">No mystery ingredients. No assumptions. Just a commitment to sharing verified product information.</SectionHeading><Ingredients/></section>
    <HowToOrder/>
    <section className="why-section"><div className="container why-grid"><div><span className="eyebrow">THE BLESSING APPROACH</span><h2>Nature inspires us.<br/><em>Your trust guides us.</em></h2><p>We believe choosing a wellness product should feel comfortable, informed and personal.</p><Link className="text-link" href="/contact">Get to know us through a conversation →</Link></div><div className="why-list">{[['Clear information', 'Know what is confirmed and what still needs a conversation.'], ['Discreet communication', 'A personal space to enquire without pressure.'], ['Customer assistance', 'Ask about your order, payment and delivery directly.'], ['Responsible wellness', 'No miracle promises. A commitment to informed choices.']].map(([title, text]) => <article key={title}><span aria-hidden="true">✓</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <Testimonials/><section className="section container faq-section"><div><SectionHeading eyebrow="A LITTLE CLARITY" title="Good questions. Thoughtful answers."/><Link className="text-link" href="/faq">Explore all FAQs →</Link></div><FAQAccordion/></section><FinalCTA/><div className="container"><DisclaimerNotice/></div></>; }
