import Link from 'next/link';
import Image from 'next/image';
import { business, disclaimer, navLinks, policyLinks, type Product } from '@/lib/business';
import { faqs } from '@/lib/content';
import { MobileNavigation, OrderPanel, ProductGallery, WhatsAppOrderButton } from './interactive';

export function BrandMark() { return <Link href="/" className="brand" aria-label="Blessing Herbal Wellness home">{business.logo ? <Image src={business.logo} alt={business.name} width={180} height={55}/> : <><span className="brand-monogram" aria-hidden="true">B<span>•</span></span><span>Blessing<small>HERBAL WELLNESS</small></span></>}</Link>; }
export function Header() { return <><div className="announcement">{business.announcement}<span>FOR ADULTS 18+</span></div><header className="header"><div className="container header-inner"><BrandMark/><nav className="desktop-nav" aria-label="Main navigation">{navLinks.map(([label, href]) => <Link href={href} key={href}>{label}</Link>)}</nav><WhatsAppOrderButton className="header-order">Order Now</WhatsAppOrderButton><MobileNavigation/></div></header></>; }
export function SocialLinks() { return <>{business.instagram ? <a href={business.instagram} target="_blank" rel="noopener noreferrer">Instagram ↗</a> : <span className="small">Instagram · link coming soon</span>}</>; }
export function Footer() { return <footer><div className="container footer-grid"><div><BrandMark/><p>{business.tagline}</p><p className="small">Thoughtful herbal wellness for adult men.<br/>Personal service, from enquiry to order.</p></div><div><h3>Explore</h3>{navLinks.map(([label, href]) => <Link href={href} key={href}>{label}</Link>)}</div><div><h3>Good to know</h3>{policyLinks.map(([label, href]) => <Link href={href} key={href}>{label}</Link>)}</div><div><h3>Stay connected</h3><WhatsAppOrderButton className="text-button">Chat on WhatsApp</WhatsAppOrderButton><SocialLinks/><span className="small">{business.hours || 'Operating hours · to be confirmed'}</span></div></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} {business.name}.</p><p>{disclaimer}</p></div></footer>; }
export function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children && <p>{children}</p>}</div>; }
export function DisclaimerNotice() { return <aside className="disclaimer"><span aria-hidden="true">ⓘ</span><div><p>{disclaimer}</p><p>If you take medication or manage a health condition, consult an appropriate healthcare professional before use. <Link href="/disclaimer">Read the full disclaimer →</Link></p></div></aside>; }
export function FAQAccordion({ items = faqs }: { items?: typeof faqs }) { return <div className="faq-list">{items.map((item, i) => <details key={item.question}><summary><span className="faq-number">{String(i + 1).padStart(2, '0')}</span>{item.question}<span className="faq-plus" aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div>; }
export function EmptyState({ title, children }: { title: string; children: React.ReactNode }) { return <div className="empty-state"><span className="eyebrow">INFORMATION PENDING</span><h3>{title}</h3><p>{children}</p></div>; }
export function Ingredients() { return business.product.ingredients.length ? <div className="ingredient-grid">{business.product.ingredients.map(ingredient => <article key={ingredient.name}>{ingredient.image && <Image src={ingredient.image} alt={ingredient.name} width={300} height={240}/>}<h3>{ingredient.name}</h3><p>{ingredient.description}</p><p>{ingredient.role}</p></article>)}</div> : <EmptyState title="Good ingredients deserve clear information.">Verified ingredients and their roles in the formulation are awaiting confirmation. Please request the current product label before ordering. Botanical styling on this site does not represent the formulation.</EmptyState>; }
export function ProductCard() { return <section className="section container product-spotlight" id="shop"><ProductGallery/><div><span className="eyebrow">MEET YOUR WELLNESS COMPANION</span><h2>{business.product.name}</h2><p>{business.product.description}</p><div className="product-tags"><span>Adult men · 18+</span><span>Herbal wellness</span></div><OrderPanel/><Link href="/product" className="text-link">Explore full product details <span aria-hidden="true">→</span></Link></div></section>; }
export function HowToOrder() { return <section className="section container"><SectionHeading eyebrow="PERSONAL. SIMPLE. DISCREET." title="Your wellness, in three steps."/><div className="steps">{[['Choose your quantity', 'Select how many units you would like to order.'], ['Start a conversation', 'Send your prepared order through WhatsApp.'], ['Confirm the details', 'Agree on payment and delivery with customer support.']].map(([title, text], i) => <article key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>; }
export function FinalCTA() { return <section className="final-cta container"><span className="eyebrow">A LITTLE CARE GOES A LONG WAY</span><h2>Ready to Begin Your<br/>Wellness Journey?</h2><p>A question, an enquiry, or your next order. We’re here to help.</p><WhatsAppOrderButton>Chat With Us on WhatsApp</WhatsAppOrderButton></section>; }
export function ComplianceFields({ values = business.product.compliance }: { values?: Product['compliance'] }) { const labels = { nafdac: 'NAFDAC registration number', batch: 'Batch number', manufactured: 'Manufacturing date', expires: 'Expiry date', manufacturer: 'Manufacturer' }; const entries = Object.entries(values).filter(([, value]) => value?.trim()); return entries.length ? <dl className="compliance">{entries.map(([key, value]) => <div key={key}><dt>{labels[key as keyof typeof labels]}</dt><dd>{value}</dd></div>)}</dl> : null; }
// Disabled intentionally. Publish only genuine customer feedback with documented permission.
export function Testimonials() { return null; }
